tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/local.crt
        keyFile: /certs/local.key
  certificates:
    - certFile: /certs/local.crt
      keyFile: /certs/local.key
      stores:
        - default
